### ISSUE TITLE
Fail if any check has been failures

### ISSUE THREAD

**Issue by timocov** [codechecks/monorepo#22] opened 2019-08-15 08:02 UTC
Currently if you run `codechecks` it always exited with code 0, even if any check is failed. I'm not sure, but I believe CLI should fail in that case as well.

**Comment by timocov** [comment] 2019-08-15 08:08
Or maybe don't fail if run is for PR and fail for local runs only...

**Comment by krzkaczor** [comment] 2019-08-15 09:51
Yeah, propagating fail locally makes total sense to me, thanks for this idea. On CI I don't think that this is a necessary behaviour since PR will be marked as failed by Checks API.

**Comment by krzkaczor** [comment] 2019-08-22 17:48
@MichalZalecki this is something that you can work on

**Comment by MichalZalecki** [comment] 2019-08-22 20:31
@krzkaczor Will look into that 👌

**Comment by MichalZalecki** [comment] 2019-08-22 20:39
btw. you can assign me to it's clear this feature is worked on

**Comment by krzkaczor** [comment] 2019-08-22 20:47
@MichalZalecki the problem is unless you make a comment I cant 😆

**Comment by MichalZalecki** [comment] 2019-08-23 14:50
@krzkaczor I see how it might be better to implement it as an opt-in behavior with default consistent what CI providers are doing. The flag could be called `--fail-fast` (RSpec) or `--bail` (Jest).

**Comment by krzkaczor** [comment] 2019-08-23 16:05
@MichalZalecki yeah I agree, this might be a little bit more flexible. We just need to make sure to document it properly in docs (people can search for something around git hooks subject).

As for the name, I think `--fail-fast` or `--bail` have a little bit different meaning because this option would be more about error propagation... maybe `exitOnError`? But I don't have strong opinion about it...

**Comment by timocov** [comment] 2019-08-26 10:45
I'm not sure that `--fail-fast` is what I'm looking for (but it's helpful though). I don't want to stop checks execution if one on them is failed - I want to fail the whole execution if one of them is failed, but all others should report their status as well.

**Comment by MichalZalecki** [comment] 2019-08-26 10:48
Ok, I understand. I might be me missing something. We would have to start keeping reports from check plugins in the state which we don't ATM.

**Comment by krzkaczor** [comment] 2019-08-26 13:35
@MichalZalecki @timocov yes I think we got two features mixed in this issue. 

First one is what @timocov originally described here. One can rephrase it as "if any check(plugin) created report with `status === "failure"` then exit code of CLI should be `!== 0`. This is something that could be hidden behind `--exitOnError` flag. If anyone has a better name let me know ;) As @MichalZalecki mentioned, it would require us to keep a local state of submitted reports somewhere.

The second feature, is what @MichalZalecki implemented which is equivalent of mocha's `--bail`. "if any check(plugin) created a report with `status === "failure"` then CLI should stop executing next check". 

Both are useful and both should be implemented. I am gonna review @MichalZalecki  PR and see if it makes sense to add (1) feature there or we should merge it first and then work on (1) in a separate stream of work.

**Comment by timocov** [comment] 2019-08-27 07:37
I believe this issue should be re-opened :)

**Comment by timocov** [comment] 2019-08-27 15:28
> Especially it can now be used as git hook

Yep, but it's good to show all errors related to the all code (like linters do for example), not only the first error in the git hook and "ask" developers to fix it and then run all hooks again to see what's next is failing - just to save our time and show all errors related to the changes :)

IMO `fail-fast` is good when you just need to detect whether everything is good or not, without thinking about what exactly is going wrong.

**Closed** 2019-09-22 22:32 UTC

**Comment by krzkaczor** [comment] 2019-09-22 22:46
Finally released as `@codechecks/client@0.1.10` Kudos to @MichalZalecki. 

There is a new flag `--with-exit-status` or simply `-x`.

**Comment by timocov** [comment] 2019-09-23 07:33
@MichalZalecki @krzkaczor Thank you guys for your work! Codechecks is really awesome tool.

I just read your discussion in the PR - is there a reason why this flag is not enabled by default for non-CI runs (only for them)?

**Comment by MichalZalecki** [comment] 2019-09-23 07:34
I'm also leaning towards making it a default behavior as discussed in #46

**Comment by krzkaczor** [comment] 2019-09-23 12:21
I got your feedback loud and clear (also @recmo noted that this would be expected behavior for him). I guess I was too focused on my initial, outdated vision.

I am fine with making this default behavior and introducing the opposite flag in `0.2.x`.
